"""New migration

Revision ID: 04c9025bfaf4
Revises: 4820624fe265
Create Date: 2024-06-23 00:15:01.982257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c9025bfaf4'
down_revision = '4820624fe265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_by', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('disease_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('FK__approved___Disea__30242045', type_='foreignkey')
        batch_op.drop_constraint('FK__approved___User___3118447E', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['Id'])
        batch_op.create_foreign_key(None, 'disease', ['disease_id'], ['Id'])
        batch_op.drop_column('Disease_Id')
        batch_op.drop_column('User_Id')

    with op.batch_alter_table('disease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ListOfSymptoms', sa.String(length=377), nullable=False))
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_column('ListOfDisease')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Username',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('Username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    with op.batch_alter_table('disease', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ListOfDisease', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False))
        batch_op.alter_column('Description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)
        batch_op.drop_column('ListOfSymptoms')
        batch_op.drop_column('Name')

    with op.batch_alter_table('approved_by', schema=None) as batch_op:
        batch_op.add_column(sa.Column('User_Id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Disease_Id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('FK__approved___User___3118447E', 'user', ['User_Id'], ['Id'])
        batch_op.create_foreign_key('FK__approved___Disea__30242045', 'disease', ['Disease_Id'], ['Id'])
        batch_op.drop_column('disease_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
