"""New migration12213

Revision ID: 0e728c390556
Revises: 04c9025bfaf4
Create Date: 2024-06-23 00:20:25.213440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e728c390556'
down_revision = '04c9025bfaf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites_to_system',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Invite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('disease',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('ListOfSymptoms', sa.String(length=377), nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('approved_by',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_by')
    op.drop_table('disease')
    op.drop_table('user')
    op.drop_table('invites_to_system')
    # ### end Alembic commands ###
