"""deleted

Revision ID: 2a07acd6a018
Revises: 2ec7aff798ca
Create Date: 2024-06-23 15:20:53.474334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a07acd6a018'
down_revision = '2ec7aff798ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites_to_system', schema=None) as batch_op:
        batch_op.drop_column('ID')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites_to_system', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
