"""empty message

Revision ID: 2ec7aff798ca
Revises: 0e728c390556
Create Date: 2024-06-23 13:14:30.613885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec7aff798ca'
down_revision = '0e728c390556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites_to_system', schema=None) as batch_op:
        batch_op.alter_column('Invite',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invites_to_system', schema=None) as batch_op:
        batch_op.alter_column('Invite',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=False)

    # ### end Alembic commands ###
