"""deleted

Revision ID: 5fabe29aad5d
Revises: 2a07acd6a018
Create Date: 2024-06-23 15:26:30.147184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fabe29aad5d'
down_revision = '2a07acd6a018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invites_to_system',
    sa.Column('Invite', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('Invite')
    )
    op.create_table('user',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('disease',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.Column('ListOfSymptoms', sa.String(length=377), nullable=False),
    sa.Column('User_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_Id'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('approved_by',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.Id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.Id'], ),
    sa.PrimaryKeyConstraint('user_id', 'disease_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_by')
    op.drop_table('disease')
    op.drop_table('user')
    op.drop_table('invites_to_system')
    # ### end Alembic commands ###
