"""New table

Revision ID: 664ec915027a
Revises: cb400a2b16f9
Create Date: 2024-06-26 14:07:09.716381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '664ec915027a'
down_revision = 'cb400a2b16f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_request',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_request')
    # ### end Alembic commands ###
